---
- set_fact:
    host_x_host: "{{ ansible_play_hosts_all }}"

- block:
    - name: Cambio de nombre a la VM VirtuaBox.
      become: true
      shell: "hostnamectl set-hostname {{ vmnnhn.split('.')[0] }}"
      loop: "{{ host_x_host }}"
      loop_control:
        loop_var: vmnnhn


