ยก---
- block:
    - name: Iniciar Maquina VM {{ vmostype }} - {{ vmname }} en VirtuaBox
      shell: |
        VBoxManage startvm {{ vmname }} --type headless
        sleep 30
      register: vbxvm_sttup
