---
- block:
    - name: Iniciar Maquina VM {{ vmostype }} - {{ vmname }} en VirtuaBox
      shell: |
        VBoxManage startvm {{ vmname }} --type headless
        sleep 30
      register: vbxvm_sttup

- block:
    - set_fact:
        run_playbook: |
          {% if vmnet == 'Tarjeta' %}
          ['validar/red/vboxvm','mensajes/final/vboxvm']
          {% elif vmnet== 'Tarjetas' %}
          ['validar/redes/vboxvm','mensajes/final/vboxvm']
          {% endif %}
    
    - name: Inicia tareas {{ run_playbook }}
      include_tasks: "{{ tareas_a }}.yml"
      loop: "{{ run_playbook }}"
      loop_control:
        loop_var: tareas_a