---
- block:
    - name: Iniciar Maquina VM {{ vmostype }} - {{ vmname }} en VirtuaBox
      shell: |
        VBoxManage startvm {{ vmname }} --type headless
        sleep 30
      register: vbxvm_sttup

    - set_fact:
        run_playbook: |
          ['validar/redes/vboxvm',mensajes/final/vboxvm']
    
    - name: Inicia tareas {{ run_playbook }}
      include_tasks: "{{ tareas_a }}.yml"
      loop: "{{ run_playbook }}"
      loop_control:
        loop_var: tareas_a