---
- block:
    - name: Crear recursos  VM de {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: |
        VBoxManage createvm --name {{ vmname }} --ostype {{ vmostype }} --register --basefolder {{ vmdstoresso }}
        VBoxManage modifyvm {{ vmname }} --ioapic on
        VBoxManage modifyvm {{ vmname }} --cpus {{ vmcpu }}
        VBoxManage modifyvm {{ vmname }} --audio-enabled off
        VBoxManage modifyvm {{ vmname }} --memory {{ vmmem }}
        VBoxManage modifyvm {{ vmname }} --graphicscontroller vmsvga
        VBoxManage modifyvm {{ vmname }} --vram 16
        VBoxManage storagectl {{ vmname }} --name "IDE Controller" --add ide
        VBoxManage storageattach {{ vmname }} --storagectl "IDE Controller" --port 0 --device 1 --type dvddrive --medium emptydrive
        VBoxManage storagectl {{ vmname }} --name SATA --add sata --controller IntelAHCI --portcount 10
      register: vmoutputcreate
