---
- block:
    - name: Apagar Maquina VM {{ vmostype }} - {{ vmname }} en VirtuaBox
      shell: |
        VBoxManage controlvm {{ vmname }} poweroff
        sleep 30
      register: vmoutputpwoff


