---
- block:
    - name: Validar Red VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: |
          sleep 15
          VBoxManage guestproperty get {{ vmname }} /VirtualBox/GuestInfo/Net/0/V4/IP 2>/dev/null | sed 's/Value: //g'
      register: vmnipnet
