---
- block:
    - name: Validar numero de Tarjetas de Red en la VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: VBoxManage showvminfo {{ vmname }} | grep NIC | grep -v disabled | wc -l
      register: vmoutputnicn

- block:
    - set_fact:
        vmnicnum: "{{ vmoutputnicn.stdout | trim }}"

- block:
    - name: Remover Tarjeta(s) de Red en la VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: |
          {% if 1 == vmnicnum %}
            VBoxManage modifyvm {{ vmname }} --nic1 none
          {% else %}
            VBoxManage modifyvm {{ vmname }} --nic1 none --nic2 none
          {% endif %}