---
- block:
    - name: Borrar VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: |
        VBoxManage controlvm {{ vmname }} shutdown
        sleep 10
        VBoxManage unregistervm {{ vmname }} --delete
      register: vmoutputrmvm
