---
vmdstoresso: /vmbox/Virtuals
vmdstoredsk: /vmboxs/Virtuals
vmdstoretpt: /vmboxs/Templates

tower_base_url: "http://172.19.0.2:8052"
tower_organization: "bvmorg"
tower_inventory: "bvm_inventory"
tower_token: "kpcGLWlxEsVx2fSSJMCeSmwhjI9h4H"

tower_user: "{{ lookup('env','TOWER_USERNAME') }}"
tower_password: "{{ lookup('env','TOWER_PASSWORD') }}"
